micronaut:
  application:
    name: ingredientGenerator

kafka.bootstrap.servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}

app:
  generate-ingredient-delay: "PT1M"
  kafka.topic:
    ingredient-generate: ingredient-generate
